name: Go Checks

on:
  push:
    branches: [ "main" ]

permissions: {}

jobs:

  codecov:
    name: Push to main test
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@aa507d98fb11c2b4dffa1b731e0786f50fd8ec93 # v0.3.1
      with:
        report: true
        chart: true
        amend: true
      if: github.event_name == 'push'
      continue-on-error: true
